// Instagram-style filters

export interface Filter {
  id: string;
  name: string;
  adjustments: {
    brightness?: number;
    contrast?: number;
    saturation?: number;
    temperature?: number;
    hue?: number;
    exposure?: number;
    shadows?: number;
    highlights?: number;
    clarity?: number;
    vibrance?: number;
    sharpness?: number;
    blur?: number;
    noise?: number;
    vignette?: number;
    filter?: 'none' | 'grayscale' | 'sepia' | 'vintage';
  };
}

export const FILTERS: Filter[] = [
  {
    id: 'original',
    name: 'Oryginał',
    adjustments: {
      brightness: 0,
      contrast: 0,
      saturation: 0,
      temperature: 0,
      hue: 0,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
  {
    id: 'vintage',
    name: 'Vintage',
    adjustments: {
      brightness: -5,
      contrast: 10,
      saturation: -20,
      temperature: 15,
      exposure: -5,
      shadows: 10,
      highlights: -10,
      vignette: 30,
      filter: 'vintage',
    },
  },
  {
    id: 'bw',
    name: 'Czarno-biały',
    adjustments: {
      brightness: 5,
      contrast: 20,
      saturation: 0,
      clarity: 15,
      sharpness: 10,
      filter: 'grayscale',
    },
  },
  {
    id: 'sepia',
    name: 'Sepia',
    adjustments: {
      brightness: 5,
      contrast: 10,
      saturation: -10,
      temperature: 20,
      vignette: 20,
      filter: 'sepia',
    },
  },
  {
    id: 'vivid',
    name: 'Żywy',
    adjustments: {
      brightness: 5,
      contrast: 15,
      saturation: 30,
      vibrance: 20,
      clarity: 10,
      sharpness: 5,
    },
  },
  {
    id: 'dramatic',
    name: 'Dramatyczny',
    adjustments: {
      brightness: -10,
      contrast: 30,
      saturation: 10,
      shadows: -20,
      highlights: -15,
      clarity: 20,
      vignette: 40,
    },
  },
  {
    id: 'cold',
    name: 'Zimny',
    adjustments: {
      brightness: 5,
      contrast: 10,
      saturation: -5,
      temperature: -30,
      hue: 10,
      clarity: 5,
    },
  },
  {
    id: 'warm',
    name: 'Ciepły',
    adjustments: {
      brightness: 10,
      contrast: 5,
      saturation: 10,
      temperature: 35,
      exposure: 5,
      shadows: 5,
    },
  },
  {
    id: 'soft',
    name: 'Miękki',
    adjustments: {
      brightness: 10,
      contrast: -10,
      saturation: -5,
      exposure: 5,
      highlights: 10,
      blur: 2,
    },
  },
  {
    id: 'sharp',
    name: 'Ostry',
    adjustments: {
      brightness: 5,
      contrast: 20,
      saturation: 5,
      clarity: 25,
      sharpness: 30,
    },
  },
  {
    id: 'fade',
    name: 'Wyblakły',
    adjustments: {
      brightness: 15,
      contrast: -15,
      saturation: -20,
      exposure: 10,
      highlights: 20,
      shadows: 15,
    },
  },
  {
    id: 'film',
    name: 'Film',
    adjustments: {
      brightness: -5,
      contrast: 15,
      saturation: -10,
      temperature: 10,
      noise: 15,
      vignette: 25,
      clarity: 10,
    },
  },
  // === NOWE FILTRY INSTAGRAM-STYLE ===
  {
    id: 'nashville',
    name: 'Nashville',
    adjustments: {
      brightness: 0,
      contrast: 10,
      saturation: 20,
      temperature: 15,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
  {
    id: 'clarendon',
    name: 'Clarendon',
    adjustments: {
      brightness: 0,
      contrast: 30,
      saturation: 15,
      temperature: 0,
      exposure: 0,
      shadows: 20,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
  {
    id: 'gingham',
    name: 'Gingham',
    adjustments: {
      brightness: 5,
      contrast: 0,
      saturation: -20,
      temperature: -10,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
  {
    id: 'moon',
    name: 'Moon',
    adjustments: {
      brightness: 0,
      contrast: 10,
      saturation: 0,
      temperature: -30,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 5,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'grayscale',
    },
  },
  {
    id: 'lark',
    name: 'Lark',
    adjustments: {
      brightness: 10,
      contrast: -5,
      saturation: 15,
      temperature: 0,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
  {
    id: 'reyes',
    name: 'Reyes',
    adjustments: {
      brightness: 0,
      contrast: 0,
      saturation: -30,
      temperature: 10,
      exposure: 5,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
  {
    id: 'juno',
    name: 'Juno',
    adjustments: {
      brightness: 0,
      contrast: 5,
      saturation: 30,
      temperature: 10,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
  {
    id: 'slumber',
    name: 'Slumber',
    adjustments: {
      brightness: 0,
      contrast: 0,
      saturation: -10,
      temperature: 25,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 20,
      filter: 'none',
    },
  },
  {
    id: 'crema',
    name: 'Crema',
    adjustments: {
      brightness: 0,
      contrast: -5,
      saturation: -20,
      temperature: 5,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
  {
    id: 'ludwig',
    name: 'Ludwig',
    adjustments: {
      brightness: 10,
      contrast: 5,
      saturation: 10,
      temperature: 0,
      exposure: 0,
      shadows: 0,
      highlights: 0,
      clarity: 0,
      vibrance: 0,
      sharpness: 0,
      blur: 0,
      noise: 0,
      vignette: 0,
      filter: 'none',
    },
  },
];
